APIVersion: v1.13.0
omit_containers: ["dba"]
instrumentation_opt_in: false
last_used_version: v1.13.0

# You can turn off usage of the dba (phpmyadmin) container and/or
# ddev-ssh-agent containers with
# omit_containers["dba", "ddev-ssh-agent"]

# and you can opt in or out of sending instrumentation the ddev developers with
# instrumentation_opt_in: true # or false
